# List of indexing methods

also refer to [the Xarray docs](https://docs.xarray.dev/en/stable/user-guide/indexing.html)

In [1]:
import cedalion
import cedalion.datasets
import cedalion.xrutils as xrutils
import xarray as xr

In [2]:
rec = cedalion.datasets.get_fingertapping()
ts = rec["amp"]
geo3d = rec.geo3d
stim = rec.stim

In [3]:
# normal array indexing works as expected
display(ts)
ts[:,0,:] # first item along wavelength

<xarray.DataArray (channel: 28, wavelength: 2, time: 23239)> Size: 10MB
<Quantity([[[0.0913686 0.0909875 0.0910225 ... 0.0941083 0.0940129 0.0944882]
  [0.1856806 0.186377  0.1836514 ... 0.1856486 0.1850836 0.1842172]]

 [[0.227516  0.2297024 0.2261366 ... 0.2264519 0.2271665 0.226713 ]
  [0.6354927 0.637668  0.6298023 ... 0.6072068 0.6087293 0.6091066]]

 [[0.1064704 0.1066212 0.1053444 ... 0.121114  0.1205022 0.1205441]
  [0.2755033 0.2761615 0.2727006 ... 0.2911952 0.2900544 0.2909847]]

 ...

 [[0.2027881 0.1996586 0.2004866 ... 0.2318743 0.2311941 0.2330808]
  [0.4666358 0.4554404 0.4561614 ... 0.4809749 0.4812827 0.4862896]]

 [[0.4885007 0.4802285 0.4818338 ... 0.6109142 0.6108118 0.613845 ]
  [0.8457658 0.825988  0.8259648 ... 0.975894  0.9756599 0.9826459]]

 [[0.6304559 0.6284427 0.6287045 ... 0.6810626 0.6809573 0.6818709]
  [1.2285622 1.2205907 1.2190002 ... 1.2729124 1.2727222 1.2755645]]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
    source      (channel) object 224B 'S1' 'S1' 'S1' 'S1' ... 'S8' 'S8' 'S8'
    detector    (channel) object 224B 'D1' 'D2' 'D3' 'D9' ... 'D7' 'D8' 'D16'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

<xarray.DataArray (channel: 28, time: 23239)> Size: 5MB
<Quantity([[0.0913686 0.0909875 0.0910225 ... 0.0941083 0.0940129 0.0944882]
 [0.227516  0.2297024 0.2261366 ... 0.2264519 0.2271665 0.226713 ]
 [0.1064704 0.1066212 0.1053444 ... 0.121114  0.1205022 0.1205441]
 ...
 [0.2027881 0.1996586 0.2004866 ... 0.2318743 0.2311941 0.2330808]
 [0.4885007 0.4802285 0.4818338 ... 0.6109142 0.6108118 0.613845 ]
 [0.6304559 0.6284427 0.6287045 ... 0.6810626 0.6809573 0.6818709]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
    source      (channel) object 224B 'S1' 'S1' 'S1' 'S1' ... 'S8' 'S8' 'S8'
    detector    (channel) object 224B 'D1' 'D2' 'D3' 'D9' ... 'D7' 'D8' 'D16'
    wavelength  float64 8B 760.0
Attributes:
    data_type_group:  unprocessed raw

In [4]:
ts[:,:,::3000] # every 3000th time point

<xarray.DataArray (channel: 28, wavelength: 2, time: 8)> Size: 4kB
<Quantity([[[0.0913686 0.0907284 0.0909799 0.096484  0.0963254 0.0978755 0.0971495
   0.0973881]
  [0.1856806 0.1819877 0.180359  0.190375  0.1934964 0.197304  0.1892043
   0.1941105]]

 [[0.227516  0.2259981 0.2191145 0.2257933 0.2224808 0.224387  0.2252353
   0.2337061]
  [0.6354927 0.6189633 0.5944316 0.6152465 0.6063239 0.6167434 0.5968902
   0.6289392]]

 [[0.1064704 0.1106003 0.1113647 0.1181299 0.1185306 0.12127   0.122234
   0.1231769]
  [0.2755033 0.2795076 0.273957  0.288187  0.2916494 0.3014054 0.2875604
   0.3011461]]

 [[0.0794062 0.0748053 0.0724615 0.0722422 0.0708733 0.0709404 0.0701675
   0.0708531]
  [0.128716  0.1205163 0.1162186 0.1156905 0.1142392 0.1144522 0.1130079
   0.1140507]]

...

 [[0.187484  0.184221  0.1801173 0.179175  0.1779962 0.1764103 0.1753207
   0.1750773]
  [0.2424386 0.2349307 0.2277864 0.2292719 0.2281034 0.2270149 0.2250216
   0.2258399]]

 [[0.2027881 0.2103115 0.2106273 0.2227526 0.2268364 0.227802  0.2291271
   0.2376249]
  [0.4666358 0.4657702 0.4522212 0.4831012 0.4902605 0.5041136 0.4770009
   0.5136656]]

 [[0.4885007 0.5211291 0.532794  0.5610836 0.5836937 0.5948393 0.5834406
   0.5656273]
  [0.8457658 0.876043  0.8738404 0.9376701 0.9678892 0.9856668 0.9351691
   0.8747212]]

 [[0.6304559 0.6529195 0.6589913 0.6675115 0.6719286 0.6761335 0.6776644
   0.6881298]
  [1.2285622 1.2409274 1.2390135 1.2576277 1.264102  1.2721376 1.269668
   1.2924444]]], 'volt')>
Coordinates:
  * time        (time) float64 64B 0.0 384.0 768.0 ... 2.304e+03 2.688e+03
    samples     (time) int64 64B 0 3000 6000 9000 12000 15000 18000 21000
  * channel     (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
    source      (channel) object 224B 'S1' 'S1' 'S1' 'S1' ... 'S8' 'S8' 'S8'
    detector    (channel) object 224B 'D1' 'D2' 'D3' 'D9' ... 'D7' 'D8' 'D16'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

In [5]:
#lookup element by label, need to know order of dims
ts.loc["S1D1", 760, :] 

<xarray.DataArray (time: 23239)> Size: 186kB
<Quantity([0.0913686 0.0909875 0.0910225 ... 0.0941083 0.0940129 0.0944882], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
    channel     <U4 16B 'S1D1'
    source      object 8B 'S1'
    detector    object 8B 'D1'
    wavelength  float64 8B 760.0
Attributes:
    data_type_group:  unprocessed raw

In [6]:
# order independent 
ts.sel(channel="S1D1", wavelength=760) 

<xarray.DataArray (time: 23239)> Size: 186kB
<Quantity([0.0913686 0.0909875 0.0910225 ... 0.0941083 0.0940129 0.0944882], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
    channel     <U4 16B 'S1D1'
    source      object 8B 'S1'
    detector    object 8B 'D1'
    wavelength  float64 8B 760.0
Attributes:
    data_type_group:  unprocessed raw

In [7]:
ts.sel(time= (ts.time  > 10 ) & (ts.time < 60.))

<xarray.DataArray (channel: 28, wavelength: 2, time: 390)> Size: 175kB
<Quantity([[[0.0899084 0.0894057 0.0901775 ... 0.0903297 0.090175  0.0899268]
  [0.1815226 0.1818538 0.1827682 ... 0.184885  0.1850145 0.1846866]]

 [[0.2271194 0.2265271 0.2281751 ... 0.2241381 0.2243378 0.2256896]
  [0.6258998 0.6286326 0.6299954 ... 0.6222512 0.6236847 0.627199 ]]

 [[0.106186  0.1064838 0.1053833 ... 0.106494  0.1061651 0.1056465]
  [0.2714331 0.2728349 0.2736203 ... 0.2736698 0.2742193 0.2759685]]

 ...

 [[0.2022316 0.2017929 0.2027171 ... 0.1998214 0.2007051 0.202647 ]
  [0.4570127 0.4581691 0.4631743 ... 0.448159  0.4511331 0.4540838]]

 [[0.487628  0.4916749 0.4934949 ... 0.5004812 0.5035935 0.5044765]
  [0.8359521 0.8418671 0.8470044 ... 0.8385809 0.8441086 0.8474942]]

 [[0.6297619 0.6308818 0.6312802 ... 0.637311  0.6379823 0.6392407]
  [1.2148105 1.2171712 1.2189573 ... 1.2232131 1.2258861 1.2278113]]], 'volt')>
Coordinates:
  * time        (time) float64 3kB 10.11 10.24 10.37 10.5 ... 59.65 59.78 59.9
    samples     (time) int64 3kB 79 80 81 82 83 84 ... 463 464 465 466 467 468
  * channel     (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
    source      (channel) object 224B 'S1' 'S1' 'S1' 'S1' ... 'S8' 'S8' 'S8'
    detector    (channel) object 224B 'D1' 'D2' 'D3' 'D9' ... 'D7' 'D8' 'D16'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

In [8]:
# regular expression via str accessor
ts.sel(channel=ts.channel.str.match("S[2,3]D[1,2]"))

<xarray.DataArray (channel: 4, wavelength: 2, time: 23239)> Size: 1MB
<Quantity([[[0.5512474 0.5510672 0.5476283 ... 0.6179242 0.6188702 0.6187721]
  [1.125532  1.1238331 1.1119423 ... 1.1817728 1.1819598 1.1832658]]

 [[0.1765604 0.1768194 0.1764903 ... 0.1787845 0.178888  0.1790632]
  [0.3228078 0.322831  0.3219485 ... 0.3182213 0.3182161 0.3181564]]

 [[0.0577035 0.0581161 0.0575968 ... 0.0606553 0.0603812 0.0608511]
  [0.1558412 0.1549238 0.1535897 ... 0.1503445 0.1506066 0.1506666]]

 [[0.1679255 0.1679034 0.1677694 ... 0.1610538 0.1611879 0.1610764]
  [0.3205449 0.3203354 0.3196127 ... 0.2977933 0.2975577 0.2978071]]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 32B 'S2D1' 'S2D10' 'S3D2' 'S3D11'
    source      (channel) object 32B 'S2' 'S2' 'S3' 'S3'
    detector    (channel) object 32B 'D1' 'D10' 'D2' 'D11'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

use `isin` to select a fixed list of items

In [9]:
ts.sel(channel=ts.channel.isin(["S1D1", "S8D8"]))

<xarray.DataArray (channel: 2, wavelength: 2, time: 23239)> Size: 744kB
<Quantity([[[0.0913686 0.0909875 0.0910225 ... 0.0941083 0.0940129 0.0944882]
  [0.1856806 0.186377  0.1836514 ... 0.1856486 0.1850836 0.1842172]]

 [[0.4885007 0.4802285 0.4818338 ... 0.6109142 0.6108118 0.613845 ]
  [0.8457658 0.825988  0.8259648 ... 0.975894  0.9756599 0.9826459]]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 16B 'S1D1' 'S8D8'
    source      (channel) object 16B 'S1' 'S8'
    detector    (channel) object 16B 'D1' 'D8'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

`.sel` relies on an index. For some  coordinates (time, channel, wavelength) indexes are built. They are printed in bold face when the DataArray is displayed. Indexes are needed for efficient lookup but are not strictly necessary. Hence, we don't build them by default.


In [10]:

try:
    ts.sel(source="S1")
except KeyError as ex:
    print(ex)


"no index found for coordinate 'source'"



If no index is available, it can either [be build](https://docs.xarray.dev/en/v2024.07.0/generated/xarray.DataArray.set_xindex.html#xarray.DataArray.set_xindex):

In [11]:
ts_with_index = ts.set_xindex("source")
ts_with_index.sel(source="S1")

<xarray.DataArray (channel: 4, wavelength: 2, time: 23239)> Size: 1MB
<Quantity([[[0.0913686 0.0909875 0.0910225 ... 0.0941083 0.0940129 0.0944882]
  [0.1856806 0.186377  0.1836514 ... 0.1856486 0.1850836 0.1842172]]

 [[0.227516  0.2297024 0.2261366 ... 0.2264519 0.2271665 0.226713 ]
  [0.6354927 0.637668  0.6298023 ... 0.6072068 0.6087293 0.6091066]]

 [[0.1064704 0.1066212 0.1053444 ... 0.121114  0.1205022 0.1205441]
  [0.2755033 0.2761615 0.2727006 ... 0.2911952 0.2900544 0.2909847]]

 [[0.0794062 0.0794713 0.0791685 ... 0.0705146 0.0705608 0.0704029]
  [0.128716  0.1289733 0.1283794 ... 0.1129772 0.1127544 0.1127884]]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 32B 'S1D1' 'S1D2' 'S1D3' 'S1D9'
  * source      (channel) object 32B 'S1' 'S1' 'S1' 'S1'
    detector    (channel) object 32B 'D1' 'D2' 'D3' 'D9'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

 ... or one can resort to selecting with boolean masks:

In [12]:
ts.loc[ts.source == "S1"]

<xarray.DataArray (channel: 4, wavelength: 2, time: 23239)> Size: 1MB
<Quantity([[[0.0913686 0.0909875 0.0910225 ... 0.0941083 0.0940129 0.0944882]
  [0.1856806 0.186377  0.1836514 ... 0.1856486 0.1850836 0.1842172]]

 [[0.227516  0.2297024 0.2261366 ... 0.2264519 0.2271665 0.226713 ]
  [0.6354927 0.637668  0.6298023 ... 0.6072068 0.6087293 0.6091066]]

 [[0.1064704 0.1066212 0.1053444 ... 0.121114  0.1205022 0.1205441]
  [0.2755033 0.2761615 0.2727006 ... 0.2911952 0.2900544 0.2909847]]

 [[0.0794062 0.0794713 0.0791685 ... 0.0705146 0.0705608 0.0704029]
  [0.128716  0.1289733 0.1283794 ... 0.1129772 0.1127544 0.1127884]]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 32B 'S1D1' 'S1D2' 'S1D3' 'S1D9'
    source      (channel) object 32B 'S1' 'S1' 'S1' 'S1'
    detector    (channel) object 32B 'D1' 'D2' 'D3' 'D9'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

Using coordinates from one array to index another. Here we use `ts.source` to select in `geo3d` values along the 'label' dimension. Because `ts.source` belongs to the 'channel' dimension of `ts`, the resulting `xr.DataArray` has dimensions 'channel' (from ts.source) and 'digitized' (from geo3d)

In [13]:
display(geo3d)
display(ts.source)
geo3d.loc[ts.source]

<xarray.DataArray (label: 55, digitized: 3)> Size: 1kB
<Quantity([[-4.16132047e-02  2.67997753e-02  1.29904394e-01]
 [-6.47668650e-02  5.81425700e-02  9.08425774e-02]
 [-7.12055455e-02 -1.28742727e-02  1.07878609e-01]
 [-8.59043654e-02  1.89716985e-02  6.50976243e-02]
 [ 3.69417160e-02  2.74838053e-02  1.30221297e-01]
 [ 6.06513374e-02  5.88241459e-02  9.11771800e-02]
 [ 6.71277139e-02 -1.21992319e-02  1.08572549e-01]
 [ 8.18868557e-02  2.04279322e-02  6.57132511e-02]
 [-3.76195887e-02  6.32285163e-02  1.15728028e-01]
 [-4.13444506e-02 -1.17796113e-02  1.34950029e-01]
 [-7.24242465e-02  2.34729321e-02  1.03222190e-01]
 [-7.91259275e-02  5.14092912e-02  5.73700461e-02]
 [ 3.35271729e-02  6.35996834e-02  1.15838813e-01]
 [ 3.68663951e-02 -1.13971649e-02  1.35367241e-01]
 [ 6.79159270e-02  2.46825447e-02  1.03666052e-01]
 [ 7.53100881e-02  5.22688450e-02  5.78769843e-02]
 [-3.77389542e-02  3.40826581e-02  1.29491979e-01]
 [-6.14543079e-02  6.44380021e-02  9.06100423e-02]
 [-7.28287898e-02 -5.27870528e-03  1.07430548e-01]
 [-8.43961064e-02  2.70612338e-02  6.55951074e-02]
...
 [-5.79890996e-02 -1.31766082e-02  1.22934918e-01]
 [-7.41954904e-02  5.49319712e-03  1.06691588e-01]
 [ 2.38285893e-02  3.99629390e-03  1.40819602e-01]
 [-8.18419575e-02  2.20987637e-02  8.42248565e-02]
 [-8.30909098e-02  3.52083018e-02  6.10323269e-02]
 [ 2.64253358e-02  4.33752201e-02  1.29394156e-01]
 [ 3.57817707e-02  4.56804970e-02  1.23546335e-01]
 [ 3.75562777e-02  8.00119085e-03  1.34555407e-01]
 [ 5.40806338e-02  2.67050264e-02  1.18184641e-01]
 [ 6.80107631e-02  2.28481808e-02  1.04458720e-01]
 [ 4.81712114e-02  6.20348289e-02  1.05182928e-01]
 [ 6.46141927e-02  4.23290866e-02  9.77770136e-02]
 [ 6.96703241e-02  5.60429038e-02  7.59091889e-02]
 [ 7.52694535e-02  3.75789197e-02  8.00743134e-02]
 [ 5.28820297e-02 -1.21396142e-02  1.24308118e-01]
 [ 6.93801362e-02  6.90166187e-03  1.08064321e-01]
 [ 7.93223927e-02 -4.48005459e-04  8.90367069e-02]
 [ 7.75602414e-02  2.25155879e-02  8.57843202e-02]
 [ 7.91230376e-02  3.64965117e-02  6.25763357e-02]
 [ 8.22582105e-02  1.75142331e-02  6.61902835e-02]], 'meter')>
Coordinates:
    type     (label) object 440B PointType.SOURCE ... PointType.LANDMARK
  * label    (label) <U3 660B 'S1' 'S2' 'S3' 'S4' 'S5' ... '25' '26' '27' '28'
Dimensions without coordinates: digitized

<xarray.DataArray 'source' (channel: 28)> Size: 224B
array(['S1', 'S1', 'S1', 'S1', 'S2', 'S2', 'S2', 'S2', 'S3', 'S3', 'S3',
       'S4', 'S4', 'S4', 'S5', 'S5', 'S5', 'S5', 'S6', 'S6', 'S6', 'S6',
       'S7', 'S7', 'S7', 'S8', 'S8', 'S8'], dtype=object)
Coordinates:
  * channel   (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
    source    (channel) object 224B 'S1' 'S1' 'S1' 'S1' ... 'S7' 'S8' 'S8' 'S8'
    detector  (channel) object 224B 'D1' 'D2' 'D3' 'D9' ... 'D7' 'D8' 'D16'

<xarray.DataArray (channel: 28, digitized: 3)> Size: 672B
<Quantity([[-0.0416132   0.02679978  0.12990439]
 [-0.0416132   0.02679978  0.12990439]
 [-0.0416132   0.02679978  0.12990439]
 [-0.0416132   0.02679978  0.12990439]
 [-0.06476686  0.05814257  0.09084258]
 [-0.06476686  0.05814257  0.09084258]
 [-0.06476686  0.05814257  0.09084258]
 [-0.06476686  0.05814257  0.09084258]
 [-0.07120555 -0.01287427  0.10787861]
 [-0.07120555 -0.01287427  0.10787861]
 [-0.07120555 -0.01287427  0.10787861]
 [-0.08590437  0.0189717   0.06509762]
 [-0.08590437  0.0189717   0.06509762]
 [-0.08590437  0.0189717   0.06509762]
 [ 0.03694172  0.02748381  0.1302213 ]
 [ 0.03694172  0.02748381  0.1302213 ]
 [ 0.03694172  0.02748381  0.1302213 ]
 [ 0.03694172  0.02748381  0.1302213 ]
 [ 0.06065134  0.05882415  0.09117718]
 [ 0.06065134  0.05882415  0.09117718]
 [ 0.06065134  0.05882415  0.09117718]
 [ 0.06065134  0.05882415  0.09117718]
 [ 0.06712771 -0.01219923  0.10857255]
 [ 0.06712771 -0.01219923  0.10857255]
 [ 0.06712771 -0.01219923  0.10857255]
 [ 0.08188686  0.02042793  0.06571325]
 [ 0.08188686  0.02042793  0.06571325]
 [ 0.08188686  0.02042793  0.06571325]], 'meter')>
Coordinates:
    type      (channel) object 224B PointType.SOURCE ... PointType.SOURCE
    label     (channel) <U3 336B 'S1' 'S1' 'S1' 'S1' ... 'S7' 'S8' 'S8' 'S8'
  * channel   (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
    source    (channel) object 224B 'S1' 'S1' 'S1' 'S1' ... 'S7' 'S8' 'S8' 'S8'
    detector  (channel) object 224B 'D1' 'D2' 'D3' 'D9' ... 'D7' 'D8' 'D16'
Dimensions without coordinates: digitized

`.sel` accepts dictionaries. Useful when dimension name is a variable

In [14]:
dim = 'wavelength'
dim_value = 760
ts.sel({dim : dim_value})

<xarray.DataArray (channel: 28, time: 23239)> Size: 5MB
<Quantity([[0.0913686 0.0909875 0.0910225 ... 0.0941083 0.0940129 0.0944882]
 [0.227516  0.2297024 0.2261366 ... 0.2264519 0.2271665 0.226713 ]
 [0.1064704 0.1066212 0.1053444 ... 0.121114  0.1205022 0.1205441]
 ...
 [0.2027881 0.1996586 0.2004866 ... 0.2318743 0.2311941 0.2330808]
 [0.4885007 0.4802285 0.4818338 ... 0.6109142 0.6108118 0.613845 ]
 [0.6304559 0.6284427 0.6287045 ... 0.6810626 0.6809573 0.6818709]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
    source      (channel) object 224B 'S1' 'S1' 'S1' 'S1' ... 'S8' 'S8' 'S8'
    detector    (channel) object 224B 'D1' 'D2' 'D3' 'D9' ... 'D7' 'D8' 'D16'
    wavelength  float64 8B 760.0
Attributes:
    data_type_group:  unprocessed raw

`geo3d` uses the name of one dimension to denote the coordinate reference system (CRS)

In [15]:
display(geo3d)
display(geo3d.points.crs) # get the name of the dimension that also names the CRS

<xarray.DataArray (label: 55, digitized: 3)> Size: 1kB
<Quantity([[-4.16132047e-02  2.67997753e-02  1.29904394e-01]
 [-6.47668650e-02  5.81425700e-02  9.08425774e-02]
 [-7.12055455e-02 -1.28742727e-02  1.07878609e-01]
 [-8.59043654e-02  1.89716985e-02  6.50976243e-02]
 [ 3.69417160e-02  2.74838053e-02  1.30221297e-01]
 [ 6.06513374e-02  5.88241459e-02  9.11771800e-02]
 [ 6.71277139e-02 -1.21992319e-02  1.08572549e-01]
 [ 8.18868557e-02  2.04279322e-02  6.57132511e-02]
 [-3.76195887e-02  6.32285163e-02  1.15728028e-01]
 [-4.13444506e-02 -1.17796113e-02  1.34950029e-01]
 [-7.24242465e-02  2.34729321e-02  1.03222190e-01]
 [-7.91259275e-02  5.14092912e-02  5.73700461e-02]
 [ 3.35271729e-02  6.35996834e-02  1.15838813e-01]
 [ 3.68663951e-02 -1.13971649e-02  1.35367241e-01]
 [ 6.79159270e-02  2.46825447e-02  1.03666052e-01]
 [ 7.53100881e-02  5.22688450e-02  5.78769843e-02]
 [-3.77389542e-02  3.40826581e-02  1.29491979e-01]
 [-6.14543079e-02  6.44380021e-02  9.06100423e-02]
 [-7.28287898e-02 -5.27870528e-03  1.07430548e-01]
 [-8.43961064e-02  2.70612338e-02  6.55951074e-02]
...
 [-5.79890996e-02 -1.31766082e-02  1.22934918e-01]
 [-7.41954904e-02  5.49319712e-03  1.06691588e-01]
 [ 2.38285893e-02  3.99629390e-03  1.40819602e-01]
 [-8.18419575e-02  2.20987637e-02  8.42248565e-02]
 [-8.30909098e-02  3.52083018e-02  6.10323269e-02]
 [ 2.64253358e-02  4.33752201e-02  1.29394156e-01]
 [ 3.57817707e-02  4.56804970e-02  1.23546335e-01]
 [ 3.75562777e-02  8.00119085e-03  1.34555407e-01]
 [ 5.40806338e-02  2.67050264e-02  1.18184641e-01]
 [ 6.80107631e-02  2.28481808e-02  1.04458720e-01]
 [ 4.81712114e-02  6.20348289e-02  1.05182928e-01]
 [ 6.46141927e-02  4.23290866e-02  9.77770136e-02]
 [ 6.96703241e-02  5.60429038e-02  7.59091889e-02]
 [ 7.52694535e-02  3.75789197e-02  8.00743134e-02]
 [ 5.28820297e-02 -1.21396142e-02  1.24308118e-01]
 [ 6.93801362e-02  6.90166187e-03  1.08064321e-01]
 [ 7.93223927e-02 -4.48005459e-04  8.90367069e-02]
 [ 7.75602414e-02  2.25155879e-02  8.57843202e-02]
 [ 7.91230376e-02  3.64965117e-02  6.25763357e-02]
 [ 8.22582105e-02  1.75142331e-02  6.61902835e-02]], 'meter')>
Coordinates:
    type     (label) object 440B PointType.SOURCE ... PointType.LANDMARK
  * label    (label) <U3 660B 'S1' 'S2' 'S3' 'S4' 'S5' ... '25' '26' '27' '28'
Dimensions without coordinates: digitized

'digitized'

In [16]:
xrutils.norm(geo3d, dim=geo3d.points.crs) # works for geo3d independent of crs

<xarray.DataArray (label: 55)> Size: 440B
<Quantity([0.13901453 0.1258081  0.12989908 0.10944033 0.13812182 0.12430665
 0.12823007 0.10696256 0.13713517 0.14163203 0.12826173 0.11043165
 0.13633643 0.14075978 0.12636634 0.10841304 0.13911876 0.12703963
 0.12989696 0.1102621  0.13814866 0.12304074 0.12830931 0.10698101
 0.08248999 0.11404664 0.08249    0.13740146 0.14092086 0.13394947
 0.13733686 0.13206607 0.12621432 0.11939553 0.13712848 0.13656263
 0.13007014 0.14287733 0.11950016 0.10894342 0.1390056  0.13649447
 0.1399273  0.13268565 0.12672461 0.1312716  0.12460774 0.11729009
 0.11614457 0.13563328 0.12860456 0.11924671 0.11781975 0.1072765
 0.10702483], 'meter')>
Coordinates:
    type     (label) object 440B PointType.SOURCE ... PointType.LANDMARK
  * label    (label) <U3 660B 'S1' 'S2' 'S3' 'S4' 'S5' ... '25' '26' '27' '28'

Splitting by distance criterium

In [17]:
dists = xrutils.norm(
        geo3d.loc[ts.source] - geo3d.loc[ts.detector], dim=geo3d.points.crs
)

mask = dists < 1.5 * cedalion.units.cm
display(ts.sel(channel=mask))
display(ts.sel(channel=~mask)) # logical not on boolean mask

<xarray.DataArray (channel: 8, wavelength: 2, time: 23239)> Size: 3MB
<Quantity([[[0.0794062 0.0794713 0.0791685 ... 0.0705146 0.0705608 0.0704029]
  [0.128716  0.1289733 0.1283794 ... 0.1129772 0.1127544 0.1127884]]

 [[0.1765604 0.1768194 0.1764903 ... 0.1787845 0.178888  0.1790632]
  [0.3228078 0.322831  0.3219485 ... 0.3182213 0.3182161 0.3181564]]

 [[0.1679255 0.1679034 0.1677694 ... 0.1610538 0.1611879 0.1610764]
  [0.3205449 0.3203354 0.3196127 ... 0.2977933 0.2975577 0.2978071]]

 ...

 [[0.2187436 0.218156  0.2175059 ... 0.2291413 0.2288382 0.2290842]
  [0.2441694 0.2429117 0.2419861 ... 0.2486965 0.2488021 0.249781 ]]

 [[0.187484  0.1868235 0.1866562 ... 0.1735965 0.1736705 0.1738339]
  [0.2424386 0.241503  0.2408491 ... 0.22303   0.2229887 0.2234081]]

 [[0.6304559 0.6284427 0.6287045 ... 0.6810626 0.6809573 0.6818709]
  [1.2285622 1.2205907 1.2190002 ... 1.2729124 1.2727222 1.2755645]]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 64B 'S1D9' 'S2D10' 'S3D11' ... 'S7D15' 'S8D16'
    source      (channel) object 64B 'S1' 'S2' 'S3' 'S4' 'S5' 'S6' 'S7' 'S8'
    detector    (channel) object 64B 'D9' 'D10' 'D11' ... 'D14' 'D15' 'D16'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

<xarray.DataArray (channel: 20, wavelength: 2, time: 23239)> Size: 7MB
<Quantity([[[0.0913686 0.0909875 0.0910225 ... 0.0941083 0.0940129 0.0944882]
  [0.1856806 0.186377  0.1836514 ... 0.1856486 0.1850836 0.1842172]]

 [[0.227516  0.2297024 0.2261366 ... 0.2264519 0.2271665 0.226713 ]
  [0.6354927 0.637668  0.6298023 ... 0.6072068 0.6087293 0.6091066]]

 [[0.1064704 0.1066212 0.1053444 ... 0.121114  0.1205022 0.1205441]
  [0.2755033 0.2761615 0.2727006 ... 0.2911952 0.2900544 0.2909847]]

 ...

 [[0.2225884 0.2187791 0.2195495 ... 0.2564863 0.2551258 0.2560233]
  [0.3994258 0.3917637 0.389261  ... 0.4304597 0.430814  0.4331249]]

 [[0.2027881 0.1996586 0.2004866 ... 0.2318743 0.2311941 0.2330808]
  [0.4666358 0.4554404 0.4561614 ... 0.4809749 0.4812827 0.4862896]]

 [[0.4885007 0.4802285 0.4818338 ... 0.6109142 0.6108118 0.613845 ]
  [0.8457658 0.825988  0.8259648 ... 0.975894  0.9756599 0.9826459]]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 160B 'S1D1' 'S1D2' 'S1D3' ... 'S8D7' 'S8D8'
    source      (channel) object 160B 'S1' 'S1' 'S1' 'S2' ... 'S7' 'S8' 'S8'
    detector    (channel) object 160B 'D1' 'D2' 'D3' 'D1' ... 'D7' 'D7' 'D8'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

changing the order of dimensions

In [18]:
display(ts)
display(ts.transpose("time", "wavelength", "channel"))

<xarray.DataArray (channel: 28, wavelength: 2, time: 23239)> Size: 10MB
<Quantity([[[0.0913686 0.0909875 0.0910225 ... 0.0941083 0.0940129 0.0944882]
  [0.1856806 0.186377  0.1836514 ... 0.1856486 0.1850836 0.1842172]]

 [[0.227516  0.2297024 0.2261366 ... 0.2264519 0.2271665 0.226713 ]
  [0.6354927 0.637668  0.6298023 ... 0.6072068 0.6087293 0.6091066]]

 [[0.1064704 0.1066212 0.1053444 ... 0.121114  0.1205022 0.1205441]
  [0.2755033 0.2761615 0.2727006 ... 0.2911952 0.2900544 0.2909847]]

 ...

 [[0.2027881 0.1996586 0.2004866 ... 0.2318743 0.2311941 0.2330808]
  [0.4666358 0.4554404 0.4561614 ... 0.4809749 0.4812827 0.4862896]]

 [[0.4885007 0.4802285 0.4818338 ... 0.6109142 0.6108118 0.613845 ]
  [0.8457658 0.825988  0.8259648 ... 0.975894  0.9756599 0.9826459]]

 [[0.6304559 0.6284427 0.6287045 ... 0.6810626 0.6809573 0.6818709]
  [1.2285622 1.2205907 1.2190002 ... 1.2729124 1.2727222 1.2755645]]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
    source      (channel) object 224B 'S1' 'S1' 'S1' 'S1' ... 'S8' 'S8' 'S8'
    detector    (channel) object 224B 'D1' 'D2' 'D3' 'D9' ... 'D7' 'D8' 'D16'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

<xarray.DataArray (time: 23239, wavelength: 2, channel: 28)> Size: 10MB
<Quantity([[[0.0913686 0.227516  0.1064704 ... 0.2027881 0.4885007 0.6304559]
  [0.1856806 0.6354927 0.2755033 ... 0.4666358 0.8457658 1.2285622]]

 [[0.0909875 0.2297024 0.1066212 ... 0.1996586 0.4802285 0.6284427]
  [0.186377  0.637668  0.2761615 ... 0.4554404 0.825988  1.2205907]]

 [[0.0910225 0.2261366 0.1053444 ... 0.2004866 0.4818338 0.6287045]
  [0.1836514 0.6298023 0.2727006 ... 0.4561614 0.8259648 1.2190002]]

 ...

 [[0.0941083 0.2264519 0.121114  ... 0.2318743 0.6109142 0.6810626]
  [0.1856486 0.6072068 0.2911952 ... 0.4809749 0.975894  1.2729124]]

 [[0.0940129 0.2271665 0.1205022 ... 0.2311941 0.6108118 0.6809573]
  [0.1850836 0.6087293 0.2900544 ... 0.4812827 0.9756599 1.2727222]]

 [[0.0944882 0.226713  0.1205441 ... 0.2330808 0.613845  0.6818709]
  [0.1842172 0.6091066 0.2909847 ... 0.4862896 0.9826459 1.2755645]]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
    source      (channel) object 224B 'S1' 'S1' 'S1' 'S1' ... 'S8' 'S8' 'S8'
    detector    (channel) object 224B 'D1' 'D2' 'D3' 'D9' ... 'D7' 'D8' 'D16'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

don't have to name all dims. use `...` 

In [19]:
display(ts.transpose(..., 'wavelength'))

<xarray.DataArray (channel: 28, time: 23239, wavelength: 2)> Size: 10MB
<Quantity([[[0.0913686 0.1856806]
  [0.0909875 0.186377 ]
  [0.0910225 0.1836514]
  ...
  [0.0941083 0.1856486]
  [0.0940129 0.1850836]
  [0.0944882 0.1842172]]

 [[0.227516  0.6354927]
  [0.2297024 0.637668 ]
  [0.2261366 0.6298023]
  ...
  [0.2264519 0.6072068]
  [0.2271665 0.6087293]
  [0.226713  0.6091066]]

 [[0.1064704 0.2755033]
  [0.1066212 0.2761615]
  [0.1053444 0.2727006]
  ...
...
  ...
  [0.2318743 0.4809749]
  [0.2311941 0.4812827]
  [0.2330808 0.4862896]]

 [[0.4885007 0.8457658]
  [0.4802285 0.825988 ]
  [0.4818338 0.8259648]
  ...
  [0.6109142 0.975894 ]
  [0.6108118 0.9756599]
  [0.613845  0.9826459]]

 [[0.6304559 1.2285622]
  [0.6284427 1.2205907]
  [0.6287045 1.2190002]
  ...
  [0.6810626 1.2729124]
  [0.6809573 1.2727222]
  [0.6818709 1.2755645]]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
    source      (channel) object 224B 'S1' 'S1' 'S1' 'S1' ... 'S8' 'S8' 'S8'
    detector    (channel) object 224B 'D1' 'D2' 'D3' 'D9' ... 'D7' 'D8' 'D16'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

In [20]:
# coordinates are xarrays, too
display(ts.source)

<xarray.DataArray 'source' (channel: 28)> Size: 224B
array(['S1', 'S1', 'S1', 'S1', 'S2', 'S2', 'S2', 'S2', 'S3', 'S3', 'S3',
       'S4', 'S4', 'S4', 'S5', 'S5', 'S5', 'S5', 'S6', 'S6', 'S6', 'S6',
       'S7', 'S7', 'S7', 'S8', 'S8', 'S8'], dtype=object)
Coordinates:
  * channel   (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
    source    (channel) object 224B 'S1' 'S1' 'S1' 'S1' ... 'S7' 'S8' 'S8' 'S8'
    detector  (channel) object 224B 'D1' 'D2' 'D3' 'D9' ... 'D7' 'D8' 'D16'

In [21]:
# often this is not what one wants:
for src in ts.source[:3]:
    print(src)

<xarray.DataArray 'source' ()> Size: 8B
array('S1', dtype=object)
Coordinates:
    channel   <U4 16B 'S1D1'
    source    object 8B 'S1'
    detector  object 8B 'D1'
<xarray.DataArray 'source' ()> Size: 8B
array('S1', dtype=object)
Coordinates:
    channel   <U4 16B 'S1D2'
    source    object 8B 'S1'
    detector  object 8B 'D2'
<xarray.DataArray 'source' ()> Size: 8B
array('S1', dtype=object)
Coordinates:
    channel   <U4 16B 'S1D3'
    source    object 8B 'S1'
    detector  object 8B 'D3'


In [22]:
# use .values
for src in ts.source.values[:3]:
    print(src)

S1
S1
S1


In [23]:
# values used on DataArray with units yields a UnitStrippedWarning
ts.values

/opt/miniconda3/envs/cedalion_240902/lib/python3.11/site-packages/xarray/core/variable.py:338: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


array([[[0.0913686, 0.0909875, 0.0910225, ..., 0.0941083, 0.0940129,
         0.0944882],
        [0.1856806, 0.186377 , 0.1836514, ..., 0.1856486, 0.1850836,
         0.1842172]],

       [[0.227516 , 0.2297024, 0.2261366, ..., 0.2264519, 0.2271665,
         0.226713 ],
        [0.6354927, 0.637668 , 0.6298023, ..., 0.6072068, 0.6087293,
         0.6091066]],

       [[0.1064704, 0.1066212, 0.1053444, ..., 0.121114 , 0.1205022,
         0.1205441],
        [0.2755033, 0.2761615, 0.2727006, ..., 0.2911952, 0.2900544,
         0.2909847]],

       ...,

       [[0.2027881, 0.1996586, 0.2004866, ..., 0.2318743, 0.2311941,
         0.2330808],
        [0.4666358, 0.4554404, 0.4561614, ..., 0.4809749, 0.4812827,
         0.4862896]],

       [[0.4885007, 0.4802285, 0.4818338, ..., 0.6109142, 0.6108118,
         0.613845 ],
        [0.8457658, 0.825988 , 0.8259648, ..., 0.975894 , 0.9756599,
         0.9826459]],

       [[0.6304559, 0.6284427, 0.6287045, ..., 0.6810626, 0.6809573,
        

In [24]:
# use .pint.dequantify to move units into .attrs and avoid UnitStrippedWarning
ts_no_units = ts.pint.dequantify()
ts_no_units.values

array([[[0.0913686, 0.0909875, 0.0910225, ..., 0.0941083, 0.0940129,
         0.0944882],
        [0.1856806, 0.186377 , 0.1836514, ..., 0.1856486, 0.1850836,
         0.1842172]],

       [[0.227516 , 0.2297024, 0.2261366, ..., 0.2264519, 0.2271665,
         0.226713 ],
        [0.6354927, 0.637668 , 0.6298023, ..., 0.6072068, 0.6087293,
         0.6091066]],

       [[0.1064704, 0.1066212, 0.1053444, ..., 0.121114 , 0.1205022,
         0.1205441],
        [0.2755033, 0.2761615, 0.2727006, ..., 0.2911952, 0.2900544,
         0.2909847]],

       ...,

       [[0.2027881, 0.1996586, 0.2004866, ..., 0.2318743, 0.2311941,
         0.2330808],
        [0.4666358, 0.4554404, 0.4561614, ..., 0.4809749, 0.4812827,
         0.4862896]],

       [[0.4885007, 0.4802285, 0.4818338, ..., 0.6109142, 0.6108118,
         0.613845 ],
        [0.8457658, 0.825988 , 0.8259648, ..., 0.975894 , 0.9756599,
         0.9826459]],

       [[0.6304559, 0.6284427, 0.6287045, ..., 0.6810626, 0.6809573,
        

In [25]:
# single item is still an xarray with coordinates
ts[0,0,0]

<xarray.DataArray ()> Size: 8B
<Quantity(0.0913686, 'volt')>
Coordinates:
    time        float64 8B 0.0
    samples     int64 8B 0
    channel     <U4 16B 'S1D1'
    source      object 8B 'S1'
    detector    object 8B 'D1'
    wavelength  float64 8B 760.0
Attributes:
    data_type_group:  unprocessed raw

In [26]:
ts[0,0,0].item()

<Quantity(0.0913686, 'volt')>

Sometimes it is useful to stack the wavlength and channel dimension:

In [29]:
ts_flat = ts.stack({"flat_channel" : ["channel", "wavelength"]})
display(ts_flat)

<xarray.DataArray (time: 23239, flat_channel: 56)> Size: 10MB
<Quantity([[0.0913686 0.1856806 0.227516  ... 0.8457658 0.6304559 1.2285622]
 [0.0909875 0.186377  0.2297024 ... 0.825988  0.6284427 1.2205907]
 [0.0910225 0.1836514 0.2261366 ... 0.8259648 0.6287045 1.2190002]
 ...
 [0.0941083 0.1856486 0.2264519 ... 0.975894  0.6810626 1.2729124]
 [0.0940129 0.1850836 0.2271665 ... 0.9756599 0.6809573 1.2727222]
 [0.0944882 0.1842172 0.226713  ... 0.9826459 0.6818709 1.2755645]], 'volt')>
Coordinates:
  * time          (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples       (time) int64 186kB 0 1 2 3 4 ... 23234 23235 23236 23237 23238
    source        (flat_channel) object 448B 'S1' 'S1' 'S1' ... 'S8' 'S8' 'S8'
    detector      (flat_channel) object 448B 'D1' 'D1' 'D2' ... 'D8' 'D16' 'D16'
  * flat_channel  (flat_channel) object 448B MultiIndex
  * channel       (flat_channel) object 448B 'S1D1' 'S1D1' ... 'S8D16' 'S8D16'
  * wavelength    (flat_channel) float64 448B 760.0 850.0 760.0 ... 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

The resulting dimension 'flat_channel' has a `MultiIndex` that combines the former 'channel' and 'wavelength' dimension and facilitates lookups on the dimensions.

In [30]:
ts_flat.sel(channel="S1D1")

<xarray.DataArray (time: 23239, wavelength: 2)> Size: 372kB
<Quantity([[0.0913686 0.1856806]
 [0.0909875 0.186377 ]
 [0.0910225 0.1836514]
 ...
 [0.0941083 0.1856486]
 [0.0940129 0.1850836]
 [0.0944882 0.1842172]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
    source      (wavelength) object 16B 'S1' 'S1'
    detector    (wavelength) object 16B 'D1' 'D1'
  * wavelength  (wavelength) float64 16B 760.0 850.0
    channel     <U4 16B 'S1D1'
Attributes:
    data_type_group:  unprocessed raw

it also allows for easy unstacking:

In [35]:
# first operate on the flattened array then unstack
ts_flat.sel(time=ts_flat.time < 60).unstack()

<xarray.DataArray (time: 469, channel: 28, wavelength: 2)> Size: 210kB
<Quantity([[[0.0913686 0.1856806]
  [0.227516  0.6354927]
  [0.1064704 0.2755033]
  ...
  [0.2027881 0.4666358]
  [0.4885007 0.8457658]
  [0.6304559 1.2285622]]

 [[0.0909875 0.186377 ]
  [0.2297024 0.637668 ]
  [0.1066212 0.2761615]
  ...
  [0.1996586 0.4554404]
  [0.4802285 0.825988 ]
  [0.6284427 1.2205907]]

 [[0.0910225 0.1836514]
  [0.2261366 0.6298023]
  [0.1053444 0.2727006]
  ...
...
  ...
  [0.1998214 0.448159 ]
  [0.5004812 0.8385809]
  [0.637311  1.2232131]]

 [[0.090175  0.1850145]
  [0.2243378 0.6236847]
  [0.1061651 0.2742193]
  ...
  [0.2007051 0.4511331]
  [0.5035935 0.8441086]
  [0.6379823 1.2258861]]

 [[0.0899268 0.1846866]
  [0.2256896 0.627199 ]
  [0.1056465 0.2759685]
  ...
  [0.202647  0.4540838]
  [0.5044765 0.8474942]
  [0.6392407 1.2278113]]], 'volt')>
Coordinates:
  * channel     (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
  * wavelength  (wavelength) float64 16B 760.0 850.0
  * time        (time) float64 4kB 0.0 0.128 0.256 0.384 ... 59.65 59.78 59.9
    samples     (time) int64 4kB 0 1 2 3 4 5 6 7 ... 462 463 464 465 466 467 468
    source      (channel, wavelength) object 448B 'S1' 'S1' 'S1' ... 'S8' 'S8'
    detector    (channel, wavelength) object 448B 'D1' 'D1' 'D2' ... 'D16' 'D16'
Attributes:
    data_type_group:  unprocessed raw

In [34]:
# get an empty array with same dimensions and coordinates
xr.zeros_like(ts)

<xarray.DataArray (channel: 28, wavelength: 2, time: 23239)> Size: 10MB
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
    source      (channel) object 224B 'S1' 'S1' 'S1' 'S1' ... 'S8' 'S8' 'S8'
    detector    (channel) object 224B 'D1' 'D2' 'D3' 'D9' ... 'D7' 'D8' 'D16'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

In [36]:
# rename a dimension
geo3d.rename({geo3d.points.crs : "new_crs"})

<xarray.DataArray (label: 55, new_crs: 3)> Size: 1kB
<Quantity([[-4.16132047e-02  2.67997753e-02  1.29904394e-01]
 [-6.47668650e-02  5.81425700e-02  9.08425774e-02]
 [-7.12055455e-02 -1.28742727e-02  1.07878609e-01]
 [-8.59043654e-02  1.89716985e-02  6.50976243e-02]
 [ 3.69417160e-02  2.74838053e-02  1.30221297e-01]
 [ 6.06513374e-02  5.88241459e-02  9.11771800e-02]
 [ 6.71277139e-02 -1.21992319e-02  1.08572549e-01]
 [ 8.18868557e-02  2.04279322e-02  6.57132511e-02]
 [-3.76195887e-02  6.32285163e-02  1.15728028e-01]
 [-4.13444506e-02 -1.17796113e-02  1.34950029e-01]
 [-7.24242465e-02  2.34729321e-02  1.03222190e-01]
 [-7.91259275e-02  5.14092912e-02  5.73700461e-02]
 [ 3.35271729e-02  6.35996834e-02  1.15838813e-01]
 [ 3.68663951e-02 -1.13971649e-02  1.35367241e-01]
 [ 6.79159270e-02  2.46825447e-02  1.03666052e-01]
 [ 7.53100881e-02  5.22688450e-02  5.78769843e-02]
 [-3.77389542e-02  3.40826581e-02  1.29491979e-01]
 [-6.14543079e-02  6.44380021e-02  9.06100423e-02]
 [-7.28287898e-02 -5.27870528e-03  1.07430548e-01]
 [-8.43961064e-02  2.70612338e-02  6.55951074e-02]
...
 [-5.79890996e-02 -1.31766082e-02  1.22934918e-01]
 [-7.41954904e-02  5.49319712e-03  1.06691588e-01]
 [ 2.38285893e-02  3.99629390e-03  1.40819602e-01]
 [-8.18419575e-02  2.20987637e-02  8.42248565e-02]
 [-8.30909098e-02  3.52083018e-02  6.10323269e-02]
 [ 2.64253358e-02  4.33752201e-02  1.29394156e-01]
 [ 3.57817707e-02  4.56804970e-02  1.23546335e-01]
 [ 3.75562777e-02  8.00119085e-03  1.34555407e-01]
 [ 5.40806338e-02  2.67050264e-02  1.18184641e-01]
 [ 6.80107631e-02  2.28481808e-02  1.04458720e-01]
 [ 4.81712114e-02  6.20348289e-02  1.05182928e-01]
 [ 6.46141927e-02  4.23290866e-02  9.77770136e-02]
 [ 6.96703241e-02  5.60429038e-02  7.59091889e-02]
 [ 7.52694535e-02  3.75789197e-02  8.00743134e-02]
 [ 5.28820297e-02 -1.21396142e-02  1.24308118e-01]
 [ 6.93801362e-02  6.90166187e-03  1.08064321e-01]
 [ 7.93223927e-02 -4.48005459e-04  8.90367069e-02]
 [ 7.75602414e-02  2.25155879e-02  8.57843202e-02]
 [ 7.91230376e-02  3.64965117e-02  6.25763357e-02]
 [ 8.22582105e-02  1.75142331e-02  6.61902835e-02]], 'meter')>
Coordinates:
    type     (label) object 440B PointType.SOURCE ... PointType.LANDMARK
  * label    (label) <U3 660B 'S1' 'S2' 'S3' 'S4' 'S5' ... '25' '26' '27' '28'
Dimensions without coordinates: new_crs

In [38]:
# works also for renaming a coordinate
ts.rename({"samples" : "counter"})

<xarray.DataArray (channel: 28, wavelength: 2, time: 23239)> Size: 10MB
<Quantity([[[0.0913686 0.0909875 0.0910225 ... 0.0941083 0.0940129 0.0944882]
  [0.1856806 0.186377  0.1836514 ... 0.1856486 0.1850836 0.1842172]]

 [[0.227516  0.2297024 0.2261366 ... 0.2264519 0.2271665 0.226713 ]
  [0.6354927 0.637668  0.6298023 ... 0.6072068 0.6087293 0.6091066]]

 [[0.1064704 0.1066212 0.1053444 ... 0.121114  0.1205022 0.1205441]
  [0.2755033 0.2761615 0.2727006 ... 0.2911952 0.2900544 0.2909847]]

 ...

 [[0.2027881 0.1996586 0.2004866 ... 0.2318743 0.2311941 0.2330808]
  [0.4666358 0.4554404 0.4561614 ... 0.4809749 0.4812827 0.4862896]]

 [[0.4885007 0.4802285 0.4818338 ... 0.6109142 0.6108118 0.613845 ]
  [0.8457658 0.825988  0.8259648 ... 0.975894  0.9756599 0.9826459]]

 [[0.6304559 0.6284427 0.6287045 ... 0.6810626 0.6809573 0.6818709]
  [1.2285622 1.2205907 1.2190002 ... 1.2729124 1.2727222 1.2755645]]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    counter     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
    source      (channel) object 224B 'S1' 'S1' 'S1' 'S1' ... 'S8' 'S8' 'S8'
    detector    (channel) object 224B 'D1' 'D2' 'D3' 'D9' ... 'D7' 'D8' 'D16'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

In [41]:
ts.drop_vars(["source", "detector"])

<xarray.DataArray (channel: 28, wavelength: 2, time: 23239)> Size: 10MB
<Quantity([[[0.0913686 0.0909875 0.0910225 ... 0.0941083 0.0940129 0.0944882]
  [0.1856806 0.186377  0.1836514 ... 0.1856486 0.1850836 0.1842172]]

 [[0.227516  0.2297024 0.2261366 ... 0.2264519 0.2271665 0.226713 ]
  [0.6354927 0.637668  0.6298023 ... 0.6072068 0.6087293 0.6091066]]

 [[0.1064704 0.1066212 0.1053444 ... 0.121114  0.1205022 0.1205441]
  [0.2755033 0.2761615 0.2727006 ... 0.2911952 0.2900544 0.2909847]]

 ...

 [[0.2027881 0.1996586 0.2004866 ... 0.2318743 0.2311941 0.2330808]
  [0.4666358 0.4554404 0.4561614 ... 0.4809749 0.4812827 0.4862896]]

 [[0.4885007 0.4802285 0.4818338 ... 0.6109142 0.6108118 0.613845 ]
  [0.8457658 0.825988  0.8259648 ... 0.975894  0.9756599 0.9826459]]

 [[0.6304559 0.6284427 0.6287045 ... 0.6810626 0.6809573 0.6818709]
  [1.2285622 1.2205907 1.2190002 ... 1.2729124 1.2727222 1.2755645]]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw