# The Recording Container: Cedalion's main data structure and a guide to indexing  

This example notebook introduces the main data classes used by cedalion, and provides examples of how to access and index them.

## Overview

**The class `cedalion.dataclasses.Recording` is Cedalion's main data container that can be used to carry related data objects through the program.** It can store time series, masks, auxiliary timeseries, probe, headmodel and stimulus information as well as meta data about the recording.
It has the following properties:

- It resembles the [NIRS group in the snirf specification](https://github.com/fNIRS/snirf/blob/v1.1/snirf_specification.md#nirsi), which provides storage for much of the data stored in a `Recording` (e.g. time series map to [data elements](https://github.com/fNIRS/snirf/blob/v1.1/snirf_specification.md#nirsidataj), [probe](https://github.com/fNIRS/snirf/blob/v1.1/snirf_specification.md#nirsiprobe), [stimulus](https://github.com/fNIRS/snirf/blob/v1.1/snirf_specification.md#nirsistimj) and [meta data](https://github.com/fNIRS/snirf/blob/v1.1/snirf_specification.md#nirsimetadatatags) are stored per NIRS element, etc). Consequently, the methods `cedalion.io.read_snirf` and `cedalion.io.write_snirf` methods operate on lists of recordings.
- different time series and masks are stored in ordered dictionaries
  - the user differentiates time series by name
  - there is a set of canonical names used by `read_snirf` to assign names to time series
    ```
    CANONICAL_NAMES = {
          "unprocessed raw": "amp",
          "processed raw": "amp",
          "processed dOD": "od",
          "processed concentrations": "conc",
          "processed central moments": "moments",
          "processed blood flow index": "bfi",
          "processed HRF dOD": "hrf_od",
          "processed HRF central moments": "hrf_moments",
          "processed HRF concentrations": "hrf_conc",
          "processed HRF blood flow index": "hrf_bfi",
          "processed absorption coefficient": "mua",
          "processed scattering coefficient": "musp",
    }
    ```
- time series are stored in the dictionaries in the order that they were added
- convenient access to the last changed time series + canonical names -> consecutive transformations of time series without the need to specify time series by name -> workflows
- `rec[key]` is a shortcut for `rec.timeseries[key]` 
- not all information stored in a `Recording` can be stored in snirf files, e.g. for masks, the headmodel and auxiliar objects there is no provision in the snirf specification. We will probably use sidecard files or sidecar hdf groups to store these.

![Recording Container](/img/recording/rec_container_overview.png)

## Exploring the recording container fields with some example data

In [ ]:
import os
import cedalion
import cedalion.io
import cedalion.datasets
import cedalion.xrutils as xrutils
import xarray as xr

# Loading an example dataset will create a recording container. 
# Alternatively you can load your ow snirf file using cedalion.io.snirf.read_snirf(PATH_TO_FILE)
rec = cedalion.datasets.get_fingertapping()
display(rec)

### The timeseries field
we loaded raw amplitude data and can now access it:

In [ ]:
display(rec["amp"])

Since we are interested not only in raw "amp"litude data, we convert this data to concentration using the modified beer-lambert law and save it under **"conc"** in the recording container

In [ ]:
import cedalion.nirs

# define DPFs and convert to HbO/HbR using the beer lambert law law
dpf = xr.DataArray(
        [6, 6],
        dims="wavelength",
        coords={"wavelength": rec["amp"].wavelength},
    )
rec["conc"] = cedalion.nirs.beer_lambert(rec["amp"], rec.geo3d, dpf)

display(rec["conc"])

### The geo3d field
we have already used channel distances from this field to calculate the concentrations using the beer-lambert law above. 
The geo3d and geo2d fields are DataArrays of geometric points, whose "magnitude" is the 3d coordinate in 3D / 2D space. They also have two coordinates: a "label", such as "S1" for Source 1, and a "type" of PointType.Source

In [ ]:
display(rec.geo3d)

### The stim field
contains labels for any experimental stimuli that were logged during the recording. Turns out each condition in the experiment was 5 seconds long.

In [ ]:
display(rec.stim)

We can see that the trial_type was encoded numerically, which can be hard to read. If we know the experiment we can rename the stimuli using the "rename_events" function

In [ ]:
rec.stim.cd.rename_events(
        {"1.0": "control", "2.0": "Tapping/Left", "3.0": "Tapping/Right"}
    )

display(rec.stim)

### The masks field
Lastly, we create a **mask** based on an SNR threshold. A mask is a Boolean DataArray that flags each point across all coordinates as either "true" or "false", according to the metric applied. Here we use an SNR of 3 to flag all channels in the raw "amp" timeseries as "False" if their SNR is below the threshold. Since SNR is calculated across the whole time, the time dimension gets dropped. Applying this mask later on to a DataArray time series works implitly thanks to the unambiguous xarray coordinates in the mask and timeseries (here for instance the channel name). 

In [ ]:
import cedalion.sigproc.quality as quality
# SNR thresholding using the "snr" function of the quality subpackage using an SNR of 3
_, rec.masks["snr_mask"] = quality.snr(rec["amp"], 3)

display(rec.masks["snr_mask"])

### The headmodel / aux_obj field
The recording container does not yet contain a mask or head model. We load an ICBM152 atlas and create the **headmodel**

In [ ]:
import cedalion.imagereco.forward_model as fw

# load segmentation data from the icbm152 atlas
SEG_DATADIR_ic152, mask_files_ic152, landmarks_file_ic152 = cedalion.datasets.get_icbm152_segmentation()

# create forward model class for icbm152 atlas
rec.head_icbm152 = fw.TwoSurfaceHeadModel.from_surfaces(
    segmentation_dir=SEG_DATADIR_ic152,
    mask_files = mask_files_ic152,
    brain_surface_file= os.path.join(SEG_DATADIR_ic152, "mask_brain.obj"),
    landmarks_ras_file=landmarks_file_ic152,
    brain_face_count=None,
    scalp_face_count=None
)

display(rec.head_icbm152)

## xarray  DataArray Indexing and Selecting Data
xarray DataArrays in Cedalion can be indexed "as usual". For a complete documentation visit the [xarray documentation page](https://docs.xarray.dev/en/latest/user-guide/indexing.html). A brief visual overview: 

![DataArray Indexing Overview](/img/recording/dataarray_indexing_overview.png)
Below we give some examples

In [68]:
# first we pull out a time series to save time in the following
ts = rec["amp"]
display(ts)

<xarray.DataArray (channel: 28, wavelength: 2, time: 23239)> Size: 10MB
<Quantity([[[0.0913686 0.0909875 0.0910225 ... 0.0941083 0.0940129 0.0944882]
  [0.1856806 0.186377  0.1836514 ... 0.1856486 0.1850836 0.1842172]]

 [[0.227516  0.2297024 0.2261366 ... 0.2264519 0.2271665 0.226713 ]
  [0.6354927 0.637668  0.6298023 ... 0.6072068 0.6087293 0.6091066]]

 [[0.1064704 0.1066212 0.1053444 ... 0.121114  0.1205022 0.1205441]
  [0.2755033 0.2761615 0.2727006 ... 0.2911952 0.2900544 0.2909847]]

 ...

 [[0.2027881 0.1996586 0.2004866 ... 0.2318743 0.2311941 0.2330808]
  [0.4666358 0.4554404 0.4561614 ... 0.4809749 0.4812827 0.4862896]]

 [[0.4885007 0.4802285 0.4818338 ... 0.6109142 0.6108118 0.613845 ]
  [0.8457658 0.825988  0.8259648 ... 0.975894  0.9756599 0.9826459]]

 [[0.6304559 0.6284427 0.6287045 ... 0.6810626 0.6809573 0.6818709]
  [1.2285622 1.2205907 1.2190002 ... 1.2729124 1.2727222 1.2755645]]], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int32 93kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
    source      (channel) object 224B 'S1' 'S1' 'S1' 'S1' ... 'S8' 'S8' 'S8'
    detector    (channel) object 224B 'D1' 'D2' 'D3' 'D9' ... 'D7' 'D8' 'D16'
  * wavelength  (wavelength) float64 16B 760.0 850.0
Attributes:
    data_type_group:  unprocessed raw

it usually helps to know the array's **coordinates**. these can be viewed via the .coords xarray accessor. Note that multiple coordinate axes can overlap. For instance, across the time dimension we can use "time" in seconds or "samples" in integer values. Across the "channel" dimension we can index via Source-Detector pairs (e.g. "S1D1") or via only the "source" or "detector". The latter will give us all matching elements - e.g. "S1" will give us all channels that contain source S1.

In [64]:
display(ts.coords)

Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int32 93kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
  * channel     (channel) object 224B 'S1D1' 'S1D2' 'S1D3' ... 'S8D8' 'S8D16'
    source      (channel) object 224B 'S1' 'S1' 'S1' 'S1' ... 'S8' 'S8' 'S8'
    detector    (channel) object 224B 'D1' 'D2' 'D3' 'D9' ... 'D7' 'D8' 'D16'
  * wavelength  (wavelength) float64 16B 760.0 850.0

Knowing the coordinates we can also acess the items / labels on the coordinate axes directly

In [48]:
display(ts.wavelength) # wavelength dimension

display(ts.time) # time dimension

<xarray.DataArray 'wavelength' (wavelength: 2)> Size: 16B
array([760., 850.])
Coordinates:
  * wavelength  (wavelength) float64 16B 760.0 850.0

<xarray.DataArray 'time' (time: 23239)> Size: 186kB
array([0.000000e+00, 1.280000e-01, 2.560000e-01, ..., 2.974208e+03,
       2.974336e+03, 2.974464e+03])
Coordinates:
  * time     (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples  (time) int32 93kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
Attributes:
    units:    second

Now we can also 

#### Direct Bracket Indexing
... works as expected

In [ ]:
ts[:,0,:] # first item along wavelength

In [ ]:
ts[:,:,::3000] # every 3000th time point

#### Indexing by Label: .loc and .sel accessors
without using the coordinate we require knowledge of the order of dimensions in the DataArray...

In [49]:
ts.loc["S1D1", 760, :] # time series for channel S1D1 and wavelength 760nm

<xarray.DataArray (time: 23239)> Size: 186kB
<Quantity([0.0913686 0.0909875 0.0910225 ... 0.0941083 0.0940129 0.0944882], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int32 93kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
    channel     <U4 16B 'S1D1'
    source      object 8B 'S1'
    detector    object 8B 'D1'
    wavelength  float64 8B 760.0
Attributes:
    data_type_group:  unprocessed raw

... or we are more explicit, in which case the order does not matter. `.sel` relies on an index. For some  coordinates (time, channel, wavelength) indexes are built. They are printed in bold face when the DataArray is displayed. Indexes are needed for efficient lookup but are not strictly necessary. Hence, we don't always build them by default.

In [67]:
ts.sel(channel="S1D1", wavelength=760)  # the same time series as above

<xarray.DataArray (time: 23239)> Size: 186kB
<Quantity([0.0913686 0.0909875 0.0910225 ... 0.0941083 0.0940129 0.0944882], 'volt')>
Coordinates:
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int32 93kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
    channel     <U4 16B 'S1D1'
    source      object 8B 'S1'
    detector    object 8B 'D1'
    wavelength  float64 8B 760.0
Attributes:
    data_type_group:  unprocessed raw

`.sel` accepts dictionaries. Useful when dimension name is a variable

In [ ]:
dim = 'wavelength'
dim_value = 760
ts.sel({dim : dim_value})

#### Indexing using logical operations
We can, for instance, choose only those data points that come after t=10s and before t=60s:

In [ ]:
ts.sel(time= (ts.time  > 10 ) & (ts.time < 60.))

boolean masking works also with the .loc accessor

In [ ]:
ts.loc[ts.source == "S1"]

#### Indexing using stringng matching or "isin"
first via string accessor

In [ ]:
# regular expression via str accessor
ts.sel(channel=ts.channel.str.match("S[2,3]D[1,2]"))

or via the use of `isin` to select a fixed tiem or list of items

In [ ]:
# item
ts.sel(channel="S1D1")

# list of items
ts.sel(channel=ts.channel.isin(["S1D1", "S8D8"]))

#### Building indices if they are not available
Repeat: `.sel` relies on an index. For some  coordinates (time, channel, wavelength) indexes are built. They are printed in bold face when the DataArray is displayed. Indexes are needed for efficient lookup but are not strictly necessary. if we would like to index via a coordinate axis for which no index is available (here the "source" coordinate), they can [be built](https://docs.xarray.dev/en/v2024.07.0/generated/xarray.DataArray.set_xindex.html#xarray.DataArray.set_xindex):

In [ ]:
# build the index
ts_with_index = ts.set_xindex("source")
# now we can select by source index
ts_with_index.sel(source="S1")

#### Using coordinates from one array to index another
Here we use `ts.source` to select in `geo3d` values along the 'label' dimension. Because `ts.source` belongs to the 'channel' dimension of `ts`, the resulting `xr.DataArray` has dimensions 'channel' (from ts.source) and 'digitized' (from geo3d)

In [ ]:
display(geo3d)
display(ts.source)
geo3d.loc[ts.source]

### Accessing xarray DataArray values with .values
e.g. to write them to a numpy array. Example: We want to pull out the actual source names of the first 3 sources..

In [41]:
# this way of indexing will not give us what we want, as it returns another xarray with coordinates etc.
display(ts.source[:3])

# instead we use the .values accessors:
display(ts.source.values[:3])

<xarray.DataArray 'source' (channel: 3)> Size: 24B
array(['S1', 'S1', 'S1'], dtype=object)
Coordinates:
  * channel   (channel) object 24B 'S1D1' 'S1D2' 'S1D3'
    source    (channel) object 24B 'S1' 'S1' 'S1'
    detector  (channel) object 24B 'D1' 'D2' 'D3'

array(['S1', 'S1', 'S1'], dtype=object)

### Accessing single items in an xarray with .item
indexing a single item in an xarray is still an xarray with coordinates

In [42]:
display(ts[0,0,0]) # the first time point of the first channel and first wavelength in the DataArray

<xarray.DataArray ()> Size: 8B
<Quantity(0.0913686, 'volt')>
Coordinates:
    time        float64 8B 0.0
    samples     int32 4B 0
    channel     <U4 16B 'S1D1'
    source      object 8B 'S1'
    detector    object 8B 'D1'
    wavelength  float64 8B 760.0
Attributes:
    data_type_group:  unprocessed raw

<Quantity(0.0913686, 'volt')>

In [55]:
# to get just the item we use .item()
display(ts[0,0,0].item())

<Quantity(0.0913686, 'volt')>

In [59]:
# of course this also works with the .sel method
ts.sel(channel="S1D1", wavelength= "760", time = "0.0").item()

<bound method _values_method_wrapper.<locals>.func of <xarray.DataArray ()> Size: 8B
<Quantity(0.0913686, 'volt')>
Coordinates:
    time        float64 8B 0.0
    samples     int32 4B 0
    channel     <U4 16B 'S1D1'
    source      object 8B 'S1'
    detector    object 8B 'D1'
    wavelength  float64 8B 760.0
Attributes:
    data_type_group:  unprocessed raw>

In [63]:
rec["amp"].loc["S1D1", 760, "0.128"]


<xarray.DataArray ()> Size: 8B
<Quantity(0.0909875, 'volt')>
Coordinates:
    time        float64 8B 0.128
    samples     int32 4B 1
    channel     <U4 16B 'S1D1'
    source      object 8B 'S1'
    detector    object 8B 'D1'
    wavelength  float64 8B 760.0
Attributes:
    data_type_group:  unprocessed raw

In [66]:
ts.time

<xarray.DataArray 'time' (time: 23239)> Size: 186kB
array([0.000000e+00, 1.280000e-01, 2.560000e-01, ..., 2.974208e+03,
       2.974336e+03, 2.974464e+03])
Coordinates:
  * time     (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples  (time) int32 93kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
Attributes:
    units:    second